[package]
name = "winducacional-typing-desktop"
version = "1.0.0"
description = "App Windows para o Simulador de Digitação WINDUCACIONAL"
authors = ["WINDUCACIONAL"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
tauri = { version = "1.5.0", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
