export const PC_CATEGORIES = [
  {
    id: "case",
    label: "Gabinete",
    shortLabel: "CASE",
    description:
      "Define o espaço físico, o fluxo de ar e os formatos de placa-mãe, fonte e refrigeração que cabem na montagem.",
  },
  {
    id: "motherboard",
    label: "Placa-mãe",
    shortLabel: "MB",
    description:
      "Interliga todos os componentes. Soquete, memória, slots e firmware precisam conversar com o restante do computador.",
  },
  {
    id: "cpu",
    label: "Processador",
    shortLabel: "CPU",
    description:
      "Executa as instruções do sistema. O soquete, a geração, o consumo e o tipo de memória determinam a compatibilidade.",
  },
  {
    id: "cooler",
    label: "Cooler do processador",
    shortLabel: "COOLER",
    description:
      "Retira o calor da CPU. Precisa encaixar no soquete, suportar a potência térmica e caber dentro do gabinete.",
  },
  {
    id: "ram",
    label: "Memória RAM",
    shortLabel: "RAM",
    description:
      "Mantém dados de trabalho acessíveis rapidamente. Tipo, quantidade de módulos, capacidade e frequência importam.",
  },
  {
    id: "gpu",
    label: "Saída de vídeo",
    shortLabel: "GPU",
    description:
      "Gera a imagem do monitor. Pode usar o vídeo integrado da CPU ou uma placa dedicada com energia e espaço próprios.",
  },
  {
    id: "storage",
    label: "Armazenamento",
    shortLabel: "DISCO",
    description:
      "Guarda o sistema e os arquivos. HDD, SSD SATA e SSD NVMe usam conexões e velocidades diferentes.",
  },
  {
    id: "psu",
    label: "Fonte de alimentação",
    shortLabel: "FONTE",
    description:
      "Converte e distribui energia. Deve ter potência com margem de segurança, formato correto e conectores suficientes.",
  },
  {
    id: "cooling",
    label: "Ventoinhas do gabinete",
    shortLabel: "FANS",
    description:
      "Movem o ar pelo gabinete. A quantidade precisa respeitar os encaixes e dissipar o calor total dos componentes.",
  },
  {
    id: "os",
    label: "Sistema operacional",
    shortLabel: "SISTEMA",
    description:
      "É instalado no disco e inicia após o firmware. Exige capacidade, memória, inicialização segura e recursos compatíveis.",
  },
];

export const PC_PARTS = [
  {
    id: "case-airflow-510",
    category: "case",
    name: "Airflow 510",
    badge: "Espaçoso",
    description:
      "Gabinete torre média com frente ventilada e espaço generoso para placas longas e refrigeração robusta.",
    connection:
      "Recebe placas ATX, micro-ATX e mini-ITX e fontes no padrão ATX.",
    formFactors: ["ATX", "mATX", "ITX"],
    psuFormats: ["ATX"],
    maxGpuLength: 360,
    maxCoolerHeight: 170,
    radiators: [120, 240, 280, 360],
    includedFans: 3,
    maxFans: 7,
    airflow: 4,
    displaySpecs: ["ATX / mATX / ITX", "GPU até 360 mm", "3 fans inclusos"],
  },
  {
    id: "case-compact-200",
    category: "case",
    name: "Compact 200",
    badge: "Compacto",
    description:
      "Gabinete compacto para bancadas pequenas, com bom aproveitamento interno e limite maior para peças volumosas.",
    connection: "Recebe placas micro-ATX e mini-ITX e fontes no padrão ATX.",
    formFactors: ["mATX", "ITX"],
    psuFormats: ["ATX"],
    maxGpuLength: 300,
    maxCoolerHeight: 155,
    radiators: [120, 240],
    includedFans: 1,
    maxFans: 5,
    airflow: 2,
    displaySpecs: ["mATX / ITX", "GPU até 300 mm", "1 fan incluso"],
  },
  {
    id: "case-mini-glass",
    category: "case",
    name: "Mini Glass SFX",
    badge: "Mini-ITX",
    description:
      "Gabinete muito pequeno com painel de vidro. Exige peças compactas e planejamento cuidadoso de calor e cabos.",
    connection:
      "Recebe somente placas mini-ITX e fontes compactas no padrão SFX.",
    formFactors: ["ITX"],
    psuFormats: ["SFX"],
    maxGpuLength: 280,
    maxCoolerHeight: 75,
    radiators: [120, 240],
    includedFans: 0,
    maxFans: 4,
    airflow: 1,
    displaySpecs: ["Somente ITX", "Fonte SFX", "Cooler até 75 mm"],
  },
  {
    id: "mb-b550m",
    category: "motherboard",
    name: "B550M Vector",
    badge: "AM4 · DDR4",
    description:
      "Placa intermediária para Ryzen AM4, com dois slots M.2 e quatro encaixes de memória DDR4.",
    connection:
      "Soquete AM4, formato micro-ATX e slot PCIe 4.0 para placa de vídeo.",
    socket: "AM4",
    formFactor: "mATX",
    memoryType: "DDR4",
    memorySlots: 4,
    maxMemory: 128,
    maxMemorySpeed: 3600,
    cpuGenerations: ["zen3"],
    m2Slots: 2,
    m2Generation: 4,
    sataPorts: 4,
    pcieGeneration: 4,
    secureBoot: true,
    tpm: true,
    uefi: true,
    displaySpecs: ["AM4", "DDR4 até 3600 MT/s", "2 × M.2 PCIe 4.0"],
  },
  {
    id: "mb-b650-atx",
    category: "motherboard",
    name: "B650 Creator",
    badge: "AM5 · DDR5",
    description:
      "Placa ATX moderna para Ryzen AM5, com memória DDR5, três slots M.2 e ampla capacidade de expansão.",
    connection: "Soquete AM5, formato ATX e slot PCIe 4.0 para placa de vídeo.",
    socket: "AM5",
    formFactor: "ATX",
    memoryType: "DDR5",
    memorySlots: 4,
    maxMemory: 192,
    maxMemorySpeed: 6400,
    cpuGenerations: ["zen4"],
    m2Slots: 3,
    m2Generation: 4,
    sataPorts: 4,
    pcieGeneration: 4,
    secureBoot: true,
    tpm: true,
    uefi: true,
    displaySpecs: ["AM5", "DDR5 até 6400 MT/s", "3 × M.2 PCIe 4.0"],
  },
  {
    id: "mb-h610m-ddr4",
    category: "motherboard",
    name: "H610M Start",
    badge: "LGA1700 · DDR4",
    description:
      "Placa de entrada para processadores Intel de 12ª geração, com dois slots DDR4 e um slot M.2.",
    connection: "Soquete LGA1700, formato micro-ATX e slot PCIe 4.0.",
    socket: "LGA1700",
    formFactor: "mATX",
    memoryType: "DDR4",
    memorySlots: 2,
    maxMemory: 64,
    maxMemorySpeed: 3200,
    cpuGenerations: ["intel12"],
    m2Slots: 1,
    m2Generation: 3,
    sataPorts: 4,
    pcieGeneration: 4,
    secureBoot: true,
    tpm: true,
    uefi: true,
    displaySpecs: ["LGA1700", "DDR4 até 3200 MT/s", "1 × M.2 PCIe 3.0"],
  },
  {
    id: "mb-z790-atx",
    category: "motherboard",
    name: "Z790 Pro",
    badge: "LGA1700 · DDR5",
    description:
      "Placa avançada para processadores Intel recentes, com DDR5 de alta velocidade e expansão reforçada.",
    connection: "Soquete LGA1700, formato ATX e slot PCIe 5.0.",
    socket: "LGA1700",
    formFactor: "ATX",
    memoryType: "DDR5",
    memorySlots: 4,
    maxMemory: 192,
    maxMemorySpeed: 7200,
    cpuGenerations: ["intel12", "intel13"],
    m2Slots: 4,
    m2Generation: 4,
    sataPorts: 6,
    pcieGeneration: 5,
    secureBoot: true,
    tpm: true,
    uefi: true,
    displaySpecs: ["LGA1700", "DDR5 até 7200 MT/s", "PCIe 5.0"],
  },
  {
    id: "cpu-ryzen-5600",
    category: "cpu",
    name: "Ryzen 5 5600",
    badge: "6 núcleos",
    description:
      "Processador equilibrado para produtividade e jogos. Não possui vídeo integrado, portanto exige placa de vídeo dedicada.",
    connection: "Encaixa no soquete AM4 e trabalha com memória DDR4.",
    socket: "AM4",
    generation: "zen3",
    memoryTypes: ["DDR4"],
    maxMemorySpeed: 3200,
    cores: 6,
    threads: 12,
    basePower: 65,
    boostPower: 88,
    integratedGraphics: false,
    performance: 6,
    displaySpecs: ["AM4", "6c / 12t", "88 W em carga", "Sem vídeo integrado"],
  },
  {
    id: "cpu-ryzen-7700",
    category: "cpu",
    name: "Ryzen 7 7700",
    badge: "8 núcleos",
    description:
      "Processador moderno de oito núcleos, com vídeo integrado básico para uso do monitor sem placa dedicada.",
    connection: "Encaixa no soquete AM5 e trabalha com memória DDR5.",
    socket: "AM5",
    generation: "zen4",
    memoryTypes: ["DDR5"],
    maxMemorySpeed: 5200,
    cores: 8,
    threads: 16,
    basePower: 65,
    boostPower: 88,
    integratedGraphics: true,
    performance: 8,
    displaySpecs: ["AM5", "8c / 16t", "88 W em carga", "Vídeo integrado"],
  },
  {
    id: "cpu-i3-12100",
    category: "cpu",
    name: "Core i3-12100",
    badge: "4 núcleos",
    description:
      "Processador de entrada responsivo, com vídeo integrado e baixo consumo para computadores de estudo e escritório.",
    connection:
      "Encaixa no soquete LGA1700 e aceita placas DDR4 ou DDR5 compatíveis.",
    socket: "LGA1700",
    generation: "intel12",
    memoryTypes: ["DDR4", "DDR5"],
    maxMemorySpeedByType: { DDR4: 3200, DDR5: 4800 },
    cores: 4,
    threads: 8,
    basePower: 60,
    boostPower: 89,
    integratedGraphics: true,
    performance: 4,
    displaySpecs: ["LGA1700", "4c / 8t", "89 W em carga", "Vídeo integrado"],
  },
  {
    id: "cpu-i7-13700kf",
    category: "cpu",
    name: "Core i7-13700KF",
    badge: "16 núcleos",
    description:
      "Processador de alto desempenho com consumo elevado. O sufixo KF indica que não há vídeo integrado.",
    connection:
      "Encaixa no soquete LGA1700 e aceita placas DDR4 ou DDR5 compatíveis.",
    socket: "LGA1700",
    generation: "intel13",
    memoryTypes: ["DDR4", "DDR5"],
    maxMemorySpeedByType: { DDR4: 3200, DDR5: 5600 },
    cores: 16,
    threads: 24,
    basePower: 125,
    boostPower: 253,
    integratedGraphics: false,
    performance: 10,
    displaySpecs: [
      "LGA1700",
      "16c / 24t",
      "253 W em turbo",
      "Sem vídeo integrado",
    ],
  },
  {
    id: "cooler-air-95",
    category: "cooler",
    name: "Air 95",
    badge: "Até 95 W",
    description:
      "Cooler a ar compacto para processadores de consumo moderado. É silencioso quando usado dentro do seu limite térmico.",
    connection: "Inclui suportes AM4 e AM5 e ocupa 150 mm de altura.",
    sockets: ["AM4", "AM5"],
    maxPower: 95,
    type: "air",
    height: 150,
    displaySpecs: ["AM4 / AM5", "Capacidade de 95 W", "150 mm de altura"],
  },
  {
    id: "cooler-tower-180",
    category: "cooler",
    name: "Tower 180",
    badge: "Até 180 W",
    description:
      "Torre de dissipação com ventoinha de 120 mm, adequada para CPUs intermediárias e avançadas.",
    connection: "Inclui suportes AM4, AM5 e LGA1700 e ocupa 158 mm de altura.",
    sockets: ["AM4", "AM5", "LGA1700"],
    maxPower: 180,
    type: "air",
    height: 158,
    displaySpecs: ["AM4 / AM5 / LGA1700", "Capacidade de 180 W", "158 mm"],
  },
  {
    id: "cooler-liquid-240",
    category: "cooler",
    name: "Liquid 240",
    badge: "Radiador 240 mm",
    description:
      "Sistema líquido selado para cargas térmicas altas. Depende de um encaixe de radiador compatível no gabinete.",
    connection: "Inclui suportes AM4, AM5 e LGA1700 e usa radiador de 240 mm.",
    sockets: ["AM4", "AM5", "LGA1700"],
    maxPower: 280,
    type: "liquid",
    radiator: 240,
    displaySpecs: [
      "Todos os soquetes da atividade",
      "Capacidade de 280 W",
      "Radiador 240 mm",
    ],
  },
  {
    id: "cooler-low-80",
    category: "cooler",
    name: "Low Profile 80",
    badge: "65 mm",
    description:
      "Cooler baixo para gabinetes pequenos. O tamanho reduzido limita a capacidade de resfriar processadores mais quentes.",
    connection: "Inclui suportes AM5 e LGA1700 e ocupa apenas 65 mm de altura.",
    sockets: ["AM5", "LGA1700"],
    maxPower: 80,
    type: "air",
    height: 65,
    displaySpecs: ["AM5 / LGA1700", "Capacidade de 80 W", "65 mm"],
  },
  {
    id: "ram-8-ddr4-2666",
    category: "ram",
    name: "8 GB DDR4 2666",
    badge: "1 módulo",
    description:
      "Módulo único básico. Funciona em placas DDR4, mas limita multitarefa e não ativa o canal duplo.",
    connection: "Ocupa um slot DDR4 da placa-mãe.",
    memoryType: "DDR4",
    capacity: 8,
    speed: 2666,
    modules: 1,
    performance: 2,
    power: 3,
    displaySpecs: ["8 GB", "DDR4 2666 MT/s", "Canal único"],
  },
  {
    id: "ram-16-ddr4-3200",
    category: "ram",
    name: "16 GB DDR4 3200",
    badge: "2 × 8 GB",
    description:
      "Kit de dois módulos equilibrado para estudo, produtividade e jogos, com canal duplo ativado.",
    connection: "Ocupa dois slots DDR4 da placa-mãe.",
    memoryType: "DDR4",
    capacity: 16,
    speed: 3200,
    modules: 2,
    performance: 5,
    power: 6,
    displaySpecs: ["16 GB", "DDR4 3200 MT/s", "Canal duplo"],
  },
  {
    id: "ram-32-ddr4-3600",
    category: "ram",
    name: "32 GB DDR4 3600",
    badge: "2 × 16 GB",
    description:
      "Kit DDR4 de alta capacidade e frequência para multitarefa pesada e criação de conteúdo.",
    connection: "Ocupa dois slots DDR4 da placa-mãe.",
    memoryType: "DDR4",
    capacity: 32,
    speed: 3600,
    modules: 2,
    performance: 7,
    power: 8,
    displaySpecs: ["32 GB", "DDR4 3600 MT/s", "Canal duplo"],
  },
  {
    id: "ram-16-ddr5-5200",
    category: "ram",
    name: "16 GB DDR5 5200",
    badge: "2 × 8 GB",
    description:
      "Kit DDR5 de entrada com canal duplo e boa largura de banda para plataformas modernas.",
    connection: "Ocupa dois slots DDR5 da placa-mãe.",
    memoryType: "DDR5",
    capacity: 16,
    speed: 5200,
    modules: 2,
    performance: 6,
    power: 7,
    displaySpecs: ["16 GB", "DDR5 5200 MT/s", "Canal duplo"],
  },
  {
    id: "ram-32-ddr5-6000",
    category: "ram",
    name: "32 GB DDR5 6000",
    badge: "2 × 16 GB",
    description:
      "Kit rápido e espaçoso para plataformas DDR5. Pode reduzir a frequência quando CPU ou placa-mãe tiver limite menor.",
    connection: "Ocupa dois slots DDR5 da placa-mãe.",
    memoryType: "DDR5",
    capacity: 32,
    speed: 6000,
    modules: 2,
    performance: 9,
    power: 9,
    displaySpecs: ["32 GB", "DDR5 6000 MT/s", "Canal duplo"],
  },
  {
    id: "gpu-integrated",
    category: "gpu",
    name: "Vídeo integrado",
    badge: "Sem placa dedicada",
    description:
      "Usa o circuito gráfico presente em alguns processadores. Economiza energia e espaço, mas depende de a CPU oferecer esse recurso.",
    connection:
      "O monitor é conectado diretamente à saída de vídeo da placa-mãe.",
    kind: "integrated",
    power: 8,
    performance: 2,
    length: 0,
    minPsu: 0,
    connectors: [],
    pcieGeneration: 0,
    displaySpecs: ["Depende da CPU", "Baixo consumo", "Uso básico"],
  },
  {
    id: "gpu-1650",
    category: "gpu",
    name: "GTX 1650 4 GB",
    badge: "75 W",
    description:
      "Placa de vídeo compacta e econômica, adequada para atividades gráficas leves e jogos em Full HD.",
    connection: "Ocupa o slot PCIe x16 e recebe energia pelo próprio slot.",
    kind: "dedicated",
    power: 75,
    performance: 4,
    length: 200,
    minPsu: 300,
    connectors: [],
    pcieGeneration: 3,
    displaySpecs: ["4 GB", "200 mm", "Sem cabo PCIe", "Fonte mínima 300 W"],
  },
  {
    id: "gpu-3060",
    category: "gpu",
    name: "RTX 3060 12 GB",
    badge: "170 W",
    description:
      "Placa intermediária com memória ampla para jogos, modelagem e aceleração de tarefas criativas.",
    connection: "Ocupa o slot PCIe x16 e exige um conector PCIe de 8 pinos.",
    kind: "dedicated",
    power: 170,
    performance: 7,
    length: 242,
    minPsu: 550,
    connectors: ["pcie-8"],
    pcieGeneration: 4,
    displaySpecs: ["12 GB", "242 mm", "1 × PCIe 8 pinos", "Fonte mínima 550 W"],
  },
  {
    id: "gpu-4070",
    category: "gpu",
    name: "RTX 4070 12 GB",
    badge: "200 W",
    description:
      "Placa de alto desempenho para jogos e criação. Exige gabinete ventilado e fonte com conector moderno.",
    connection: "Ocupa o slot PCIe x16 e exige um conector 12VHPWR.",
    kind: "dedicated",
    power: 200,
    performance: 9,
    length: 285,
    minPsu: 650,
    connectors: ["12vhpwr"],
    pcieGeneration: 4,
    displaySpecs: ["12 GB", "285 mm", "1 × 12VHPWR", "Fonte mínima 650 W"],
  },
  {
    id: "storage-hdd-1tb",
    category: "storage",
    name: "HDD 1 TB",
    badge: "SATA · 160 MB/s",
    description:
      "Disco magnético de grande capacidade e baixo custo. É mais lento e possui partes mecânicas.",
    connection: "Usa uma porta SATA da placa-mãe e um conector SATA da fonte.",
    interface: "SATA",
    capacity: 1000,
    speed: 160,
    power: 8,
    performance: 2,
    displaySpecs: ["1 TB", "SATA III", "Até 160 MB/s"],
  },
  {
    id: "storage-ssd-480",
    category: "storage",
    name: "SSD SATA 480 GB",
    badge: "SATA · 550 MB/s",
    description:
      "SSD sem partes móveis, muito mais responsivo que um HDD e compatível com portas SATA tradicionais.",
    connection: "Usa uma porta SATA da placa-mãe e um conector SATA da fonte.",
    interface: "SATA",
    capacity: 480,
    speed: 550,
    power: 4,
    performance: 5,
    displaySpecs: ["480 GB", "SATA III", "Até 550 MB/s"],
  },
  {
    id: "storage-nvme-gen3",
    category: "storage",
    name: "SSD NVMe 1 TB Gen3",
    badge: "M.2 · 3500 MB/s",
    description:
      "SSD compacto que se conecta direto à placa-mãe e oferece alta velocidade sem cabos de dados ou energia.",
    connection: "Ocupa um slot M.2 com comunicação PCIe 3.0.",
    interface: "M2",
    generation: 3,
    capacity: 1000,
    speed: 3500,
    power: 6,
    performance: 8,
    displaySpecs: ["1 TB", "M.2 PCIe 3.0", "Até 3500 MB/s"],
  },
  {
    id: "storage-nvme-gen4",
    category: "storage",
    name: "SSD NVMe 2 TB Gen4",
    badge: "M.2 · 7000 MB/s",
    description:
      "SSD NVMe rápido e espaçoso. Em uma placa-mãe mais antiga, funciona limitado à geração disponível.",
    connection: "Ocupa um slot M.2 com comunicação PCIe 4.0.",
    interface: "M2",
    generation: 4,
    capacity: 2000,
    speed: 7000,
    power: 8,
    performance: 10,
    displaySpecs: ["2 TB", "M.2 PCIe 4.0", "Até 7000 MB/s"],
  },
  {
    id: "psu-atx-450",
    category: "psu",
    name: "Fonte 450 W Bronze",
    badge: "ATX",
    description:
      "Fonte básica eficiente para computadores de consumo moderado. Possui um conector PCIe de 8 pinos.",
    connection:
      "Formato ATX, quatro conectores SATA e um conector PCIe de 8 pinos.",
    format: "ATX",
    wattage: 450,
    efficiency: "80 Plus Bronze",
    connectors: { "pcie-8": 1, "12vhpwr": 0, sata: 4 },
    displaySpecs: ["450 W", "80 Plus Bronze", "1 × PCIe 8 pinos"],
  },
  {
    id: "psu-atx-650",
    category: "psu",
    name: "Fonte 650 W Gold",
    badge: "ATX",
    description:
      "Fonte eficiente para configurações intermediárias, com boa margem e dois conectores PCIe de 8 pinos.",
    connection:
      "Formato ATX, seis conectores SATA e dois conectores PCIe de 8 pinos.",
    format: "ATX",
    wattage: 650,
    efficiency: "80 Plus Gold",
    connectors: { "pcie-8": 2, "12vhpwr": 0, sata: 6 },
    displaySpecs: ["650 W", "80 Plus Gold", "2 × PCIe 8 pinos"],
  },
  {
    id: "psu-atx-750",
    category: "psu",
    name: "Fonte 750 W Gold ATX 3.0",
    badge: "ATX · 12VHPWR",
    description:
      "Fonte moderna com margem alta e conector nativo para placas de vídeo recentes.",
    connection: "Formato ATX, seis SATA, três PCIe de 8 pinos e um 12VHPWR.",
    format: "ATX",
    wattage: 750,
    efficiency: "80 Plus Gold",
    connectors: { "pcie-8": 3, "12vhpwr": 1, sata: 6 },
    displaySpecs: ["750 W", "80 Plus Gold", "12VHPWR nativo"],
  },
  {
    id: "psu-sfx-600",
    category: "psu",
    name: "Fonte SFX 600 W Gold",
    badge: "SFX",
    description:
      "Fonte compacta para gabinetes pequenos, com potência suficiente para placas intermediárias.",
    connection: "Formato SFX, quatro SATA e dois conectores PCIe de 8 pinos.",
    format: "SFX",
    wattage: 600,
    efficiency: "80 Plus Gold",
    connectors: { "pcie-8": 2, "12vhpwr": 0, sata: 4 },
    displaySpecs: ["600 W", "Formato SFX", "2 × PCIe 8 pinos"],
  },
  {
    id: "fans-none",
    category: "cooling",
    name: "Sem ventoinhas extras",
    badge: "Somente as inclusas",
    description:
      "Mantém apenas as ventoinhas que acompanham o gabinete. Pode ser suficiente em montagens frias e espaçosas.",
    connection: "Não ocupa conectores nem posições adicionais.",
    count: 0,
    airflow: 0,
    power: 0,
    displaySpecs: ["0 fans extras", "0 W", "Fluxo do gabinete"],
  },
  {
    id: "fans-kit-2",
    category: "cooling",
    name: "Kit com 2 fans de 120 mm",
    badge: "Fluxo balanceado",
    description:
      "Par de ventoinhas para criar entrada e saída de ar, melhorando a troca térmica dentro do gabinete.",
    connection:
      "Ocupa duas posições de 120 mm e conectores de ventoinha da placa-mãe.",
    count: 2,
    airflow: 3,
    power: 5,
    displaySpecs: ["2 × 120 mm", "5 W", "Entrada + saída"],
  },
  {
    id: "fans-kit-4",
    category: "cooling",
    name: "Kit com 4 fans de 120 mm",
    badge: "Alto fluxo",
    description:
      "Conjunto para montagens quentes. Move mais ar, mas exige quatro posições livres no gabinete.",
    connection:
      "Ocupa quatro posições de 120 mm e pode exigir um hub de ventoinhas.",
    count: 4,
    airflow: 6,
    power: 10,
    displaySpecs: ["4 × 120 mm", "10 W", "Alto fluxo"],
  },
  {
    id: "os-windows-11-education",
    category: "os",
    name: "Windows 11 Education 64 bits",
    badge: "UEFI · TPM 2.0",
    description:
      "Sistema para ambientes educacionais. Precisa de inicialização UEFI, TPM 2.0, memória e espaço livre mínimos.",
    connection:
      "É instalado no armazenamento e inicializado pelo firmware da placa-mãe.",
    minStorage: 64,
    minMemory: 4,
    requiresUefi: true,
    requiresTpm: true,
    requiresSecureBoot: true,
    displaySpecs: [
      "64 bits",
      "4 GB de RAM",
      "64 GB de disco",
      "UEFI + TPM 2.0",
    ],
  },
];

export const PC_PARTS_BY_ID = new Map(PC_PARTS.map((part) => [part.id, part]));

export const getPcPart = (id) => PC_PARTS_BY_ID.get(String(id || "")) || null;

export const getPcPartsByCategory = (category) =>
  PC_PARTS.filter((part) => part.category === category);
